version: '3.9'
services:
  spa_nginx:
    container_name: spa_nginx
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 10s
    image: ulvhed/nginx:#sha
    networks:
      lb_example:
        aliases:
          - nginx
    restart: on-failure
  spa_apache:
    container_name: spa_apache
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 10s
    image: ulvhed/apache:#sha
    networks:
      lb_example:
        aliases:
          - apache
    restart: on-failure
networks:
  lb_example:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
    
# vim:sw=2:ts=2:sts=2:et
