version: '3.9'
services:
  spa-nginx:
    build: ./docker/nginx
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 10s
  spa-apache:
    build: ./docker/apache
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 10s
