version: '3.9'

services:

  haproxy:
    container_name: haproxy
    depends_on:
      - spa_nginx
      - spa_apache
    expose:
      - 80
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 10s
    image: haproxy:2.5.3-alpine3.15
    networks:
      lb_example:
        ipv4_address: 172.28.0.10
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  spa_nginx:
    build: ./docker/nginx
    container_name: spa_nginx
    expose:
      - 80
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 10s
    networks:
      lb_example:
        ipv4_address: 172.28.0.18
        aliases:
          - nginx
    restart: on-failure

  spa_apache:
    build: ./docker/apache
    container_name: spa_apache
    expose:
      - 80
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 10s
    networks:
      lb_example:
        ipv4_address: 172.28.0.19
        aliases:
          - apache
    restart: on-failure

networks:
  lb_example:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24

# vim:sw=2:ts=2:sts=2:et
