name: Docker PR CI

on:
  pull_request:
    types: [ opened, edited, reopened, review_requested, synchronize ]

jobs:

  nginx-oci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/metadata-action@v3
      id: metadata
      with:
        images: ulvhed/lb-example-nginx
    - name: Nginx container build
      uses: int128/kaniko-action@v1
      with:
        push: false
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        context: docker/nginx

  httpd-oci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/metadata-action@v3
      id: metadata
      with:
        images: ulvhed/lb-example-httpd
    - name: Apache container build
      uses: int128/kaniko-action@v1
      with:
        push: false
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        context: docker/apache
