name: Docker PR CI

on:
  pull_request:
    types: [ opened, edited, reopened, review_requested, synchronize ]
    branches: [ $default-branch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Nginx container build
      uses: int128/kaniko-action@v1
      with:
        push: false
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        context: docker/nginx
    - name: Apache container build
      uses: int128/kaniko-action@v1
      with:
        push: false
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        context: docker/apache
